### ISSUE TITLE
Crash without using use_frameworks!

### ISSUE THREAD

**Issue by RylanJIN** [kinecosystem/kin-ecosystem-ios-sdk#16] opened 2018-09-04 02:33 UTC
I am integrating with kin ecosystem, and it works really great on your sample project, but when I remove 'use_frameworks!' (as due to some reason our App don't use this) in Podfile, it starts crashing.

I modified the Podfile, and it looks like as below: 

```
target 'EcosystemSampleApp' do

pod 'KinEcosystem'

pod 'JWT', '3.0.0-beta.8', :modular_headers => true
pod 'Base64', :modular_headers => true

end
```

and crash screen shot:

![20_06_25__08_23_2018](https://user-images.githubusercontent.com/3701605/44524572-b6069480-a710-11e8-87a4-e73ea81faf02.jpg)

**Comment by Elaz** [comment] 2018-09-13 13:45
@RylanJIN Thanks for the detailed catch.
The issue is now fixed in https://github.com/kinecosystem/kin-ecosystem-ios-sdk/releases/tag/0.5.0

**Closed** 2018-09-14 06:05 UTC
